//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/_Main/Scripts/Managers/Input/UnitInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UnitInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UnitInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UnitInputActions"",
    ""maps"": [
        {
            ""name"": ""Unit"",
            ""id"": ""b532f190-a7e0-4920-b58b-fe2dc8892833"",
            ""actions"": [
                {
                    ""name"": ""SelectUnitMultiple"",
                    ""type"": ""Value"",
                    ""id"": ""60cd80b1-cf38-4287-8a51-88f6a3945641"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""SlowTap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectUnitSingle"",
                    ""type"": ""Button"",
                    ""id"": ""3c1490be-9f04-4929-865a-8ba4f4893695"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectUnitInclusive"",
                    ""type"": ""Value"",
                    ""id"": ""fa41345d-5369-46a9-8c09-1d7b1b175582"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TakeAction"",
                    ""type"": ""Button"",
                    ""id"": ""0fcd5eed-0312-4a35-a833-d9716416aadc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2eb84647-e713-483e-a3e4-e3d721e632fd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUnitMultiple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30ef23a8-917f-4e76-98df-e2bf3c44a460"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUnitSingle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7804311c-0039-4382-b12f-39f3e4588076"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUnitInclusive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc73cf16-5024-41fe-a84c-3551dc310860"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Unit
        m_Unit = asset.FindActionMap("Unit", throwIfNotFound: true);
        m_Unit_SelectUnitMultiple = m_Unit.FindAction("SelectUnitMultiple", throwIfNotFound: true);
        m_Unit_SelectUnitSingle = m_Unit.FindAction("SelectUnitSingle", throwIfNotFound: true);
        m_Unit_SelectUnitInclusive = m_Unit.FindAction("SelectUnitInclusive", throwIfNotFound: true);
        m_Unit_TakeAction = m_Unit.FindAction("TakeAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Unit
    private readonly InputActionMap m_Unit;
    private List<IUnitActions> m_UnitActionsCallbackInterfaces = new List<IUnitActions>();
    private readonly InputAction m_Unit_SelectUnitMultiple;
    private readonly InputAction m_Unit_SelectUnitSingle;
    private readonly InputAction m_Unit_SelectUnitInclusive;
    private readonly InputAction m_Unit_TakeAction;
    public struct UnitActions
    {
        private @UnitInputActions m_Wrapper;
        public UnitActions(@UnitInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectUnitMultiple => m_Wrapper.m_Unit_SelectUnitMultiple;
        public InputAction @SelectUnitSingle => m_Wrapper.m_Unit_SelectUnitSingle;
        public InputAction @SelectUnitInclusive => m_Wrapper.m_Unit_SelectUnitInclusive;
        public InputAction @TakeAction => m_Wrapper.m_Unit_TakeAction;
        public InputActionMap Get() { return m_Wrapper.m_Unit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UnitActions set) { return set.Get(); }
        public void AddCallbacks(IUnitActions instance)
        {
            if (instance == null || m_Wrapper.m_UnitActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UnitActionsCallbackInterfaces.Add(instance);
            @SelectUnitMultiple.started += instance.OnSelectUnitMultiple;
            @SelectUnitMultiple.performed += instance.OnSelectUnitMultiple;
            @SelectUnitMultiple.canceled += instance.OnSelectUnitMultiple;
            @SelectUnitSingle.started += instance.OnSelectUnitSingle;
            @SelectUnitSingle.performed += instance.OnSelectUnitSingle;
            @SelectUnitSingle.canceled += instance.OnSelectUnitSingle;
            @SelectUnitInclusive.started += instance.OnSelectUnitInclusive;
            @SelectUnitInclusive.performed += instance.OnSelectUnitInclusive;
            @SelectUnitInclusive.canceled += instance.OnSelectUnitInclusive;
            @TakeAction.started += instance.OnTakeAction;
            @TakeAction.performed += instance.OnTakeAction;
            @TakeAction.canceled += instance.OnTakeAction;
        }

        private void UnregisterCallbacks(IUnitActions instance)
        {
            @SelectUnitMultiple.started -= instance.OnSelectUnitMultiple;
            @SelectUnitMultiple.performed -= instance.OnSelectUnitMultiple;
            @SelectUnitMultiple.canceled -= instance.OnSelectUnitMultiple;
            @SelectUnitSingle.started -= instance.OnSelectUnitSingle;
            @SelectUnitSingle.performed -= instance.OnSelectUnitSingle;
            @SelectUnitSingle.canceled -= instance.OnSelectUnitSingle;
            @SelectUnitInclusive.started -= instance.OnSelectUnitInclusive;
            @SelectUnitInclusive.performed -= instance.OnSelectUnitInclusive;
            @SelectUnitInclusive.canceled -= instance.OnSelectUnitInclusive;
            @TakeAction.started -= instance.OnTakeAction;
            @TakeAction.performed -= instance.OnTakeAction;
            @TakeAction.canceled -= instance.OnTakeAction;
        }

        public void RemoveCallbacks(IUnitActions instance)
        {
            if (m_Wrapper.m_UnitActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUnitActions instance)
        {
            foreach (var item in m_Wrapper.m_UnitActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UnitActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UnitActions @Unit => new UnitActions(this);
    public interface IUnitActions
    {
        void OnSelectUnitMultiple(InputAction.CallbackContext context);
        void OnSelectUnitSingle(InputAction.CallbackContext context);
        void OnSelectUnitInclusive(InputAction.CallbackContext context);
        void OnTakeAction(InputAction.CallbackContext context);
    }
}
